# United States - Crime Rates - 1960 - 2014

### Introduction:

This time you will create a data

Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/thieu1995/csv-files/main/data/pandas/US_Crime_Rates_1960_2014.csv).

In [2]:
url = "https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/04_Apply/US_Crime_Rates/US_Crime_Rates_1960_2014.csv"

### Step 3. Assign it to a variable called crime.

In [3]:
crime = pd.read_csv(url)

### Step 4. What is the type of the columns?

In [4]:
crime.dtypes

Year                  int64
Population            int64
Total                 int64
Violent               int64
Property              int64
Murder                int64
Forcible_Rape         int64
Robbery               int64
Aggravated_assault    int64
Burglary              int64
Larceny_Theft         int64
Vehicle_Theft         int64
dtype: object

##### Have you noticed that the type of Year is int64. But pandas has a different type to work with Time Series. Let's see it now.

### Step 5. Convert the type of the column Year to datetime64

In [5]:
crime["Year"] = pd.to_datetime(crime["Year"], format="%Y")

### Step 6. Set the Year column as the index of the dataframe

In [6]:
crime = crime.set_index("Year")

### Step 7. Delete the Total column

In [7]:
crime = crime.drop("Total", axis=1)

### Step 8. Group the year by decades and sum the values

#### Pay attention to the Population column number, summing this column is a mistake

In [8]:
crime.groupby((crime.index.year // 10) * 10).agg({
    "Population": "max",
    "Violent": "sum",
    "Murder": "sum",
    "Forcible_Rape": "sum",
    "Robbery": "sum",
    "Aggravated_assault": "sum",
    "Property": "sum",
    "Burglary": "sum",
    "Larceny_Theft": "sum",
    "Vehicle_Theft": "sum"
})

,Population,Violent,Murder,Forcible_Rape,Robbery,Aggravated_assault,Property,Burglary,Larceny_Theft,Vehicle_Theft
Year,,,,,,,,,,
1960,201385000,4134930,106180,236720,1633510,2158520,45160900,13321100,26547700,5292100
1970,220099000,9607930,192230,554570,4159020,4702120,91383800,28486000,53157800,9739900
1980,248239000,14074328,206439,865639,5383109,7619130,117048900,33073494,72040253,11935411
1990,272690813,17527048,211664,998827,5748930,10568963,119053499,26750015,77679366,14624418
2000,307006550,13968056,163068,922499,4230366,8652124,100944369,21565176,67970291,11412834
2010,318857056,6072017,72867,421059,1749809,3764142,44095950,10125170,30401698,3569080

### Step 9. What is the most dangerous decade to live in the US?

In [9]:
decade = crime.groupby((crime.index.year // 10) * 10)["Violent"].sum()
print(decade)
print("Most dangerous decade:", decade.idxmax())

Year
1960     4134930
1970     9607930
1980    14074328
1990    17527048
2000    13968056
2010     6072017
Name: Violent, dtype: int64
Most dangerous decade: 1990