# MPG Cars

### Introduction:

The following exercise utilizes data from [UC Irvine Machine Learning Repository](https://archive.ics.uci.edu/ml/datasets/Auto+MPG)

### Step 1. Import the necessary libraries

In [21]:
import pandas as pd
import numpy as np

### Step 2. Import the first dataset [cars1](https://raw.githubusercontent.com/thieu1995/csv-files/main/data/pandas/cars1.csv) and [cars2](https://raw.githubusercontent.com/thieu1995/csv-files/main/data/pandas/cars2.csv).

In [22]:
url1 = "https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars1.csv"
url2 = "https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars2.csv"

   ### Step 3. Assign each to a variable called cars1 and cars2

In [23]:
cars1 = pd.read_csv(url1)
cars2 = pd.read_csv(url2)

### Step 4. Oops, it seems our first dataset has some unnamed blank columns, fix cars1

In [24]:
cars1 = cars1.loc[:, ~cars1.columns.str.contains("^Unnamed")]

cars1

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
193,24.0,6,200,81,3012,17.6,76,1,ford maverick
194,22.5,6,232,90,3085,17.6,76,1,amc hornet
195,29.0,4,85,52,2035,22.2,76,1,chevrolet chevette
196,24.5,4,98,60,2164,22.1,76,1,chevrolet woody
197,29.0,4,90,70,1937,14.2,76,2,vw rabbit

### Step 5. What is the number of observations in each dataset?

In [25]:
cars1.shape[0]

198

### Step 6. Join cars1 and cars2 into a single DataFrame called cars

In [31]:
cars = pd.concat([cars1, cars2], ignore_index=True)
print(len(cars1))
print(len(cars2))
print(len(cars))

198
200
398

### Step 7. Oops, there is a column missing, called owners. Create a random number Series from 15,000 to 73,000.

In [32]:
owners = pd.Series(np.random.randint(15000, 73001, size=len(cars)))

### Step 8. Add the column owners to cars

In [33]:
cars["owners"] = owners

cars.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car,owners
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu,58050
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320,25651
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite,65842
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst,22052
4,17.0,8,302,140,3449,10.5,70,1,ford torino,44034