# Ex2 - Getting and Knowing your Data

This time we are going to pull data directly from the internet.
Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [4]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/thieu1995/csv-files/main/data/pandas/chipotle.tsv).

### Step 3. Assign it to a variable called chipo.

In [5]:
url = "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv"

chipo = pd.read_csv(url, sep="\t")

### Step 4. See the first 10 entries

In [6]:
chipo.head(10)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
6,3,1,Side of Chips,NaN,$1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25

### Step 5. What is the number of observations in the dataset?

In [7]:
# Solution 1

chipo.shape[0]

4622

In [8]:
# Solution 2

len(chipo)

4622

### Step 6. What is the number of columns in the dataset?

In [9]:
chipo.shape[1]

5

### Step 7. Print the name of all the columns.

In [10]:
print(chipo.columns)

Index(['order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'],
      dtype='object')

### Step 8. How is the dataset indexed?

In [11]:
chipo.index

RangeIndex(start=0, stop=4622, step=1)

### Step 9. Which was the most-ordered item?

In [12]:
chipo.groupby('item_name')['quantity'].sum().sort_values(ascending=False).head(1)

item_name
Chicken Bowl    761
Name: quantity, dtype: int64

### Step 10. For the most-ordered item, how many items were ordered?

In [13]:
chipo.groupby('item_name')['quantity'].sum().sort_values(ascending=False).iloc[0]

np.int64(761)

### Step 11. What was the most ordered item in the choice_description column?

In [14]:
chipo.groupby('choice_description')['quantity'].sum().sort_values(ascending=False).head(1)

choice_description
[Diet Coke]    159
Name: quantity, dtype: int64

### Step 12. How many items were orderd in total?

In [15]:
chipo['quantity'].sum()

np.int64(4972)

### Step 13. Turn the item price into a float

#### Step 13.a. Check the item price type

In [16]:
chipo['item_price'].dtype

dtype('O')

#### Step 13.b. Create a lambda function and change the type of item price

In [17]:
chipo['item_price'] = chipo['item_price'].apply(lambda x: float(x[1:]))

#### Step 13.c. Check the item price type

In [18]:
chipo['item_price'].dtype

dtype('float64')

### Step 14. How much was the revenue for the period in the dataset?

In [19]:
revenue = (chipo['quantity'] * chipo['item_price']).sum()
print(revenue)

39237.02

### Step 15. How many orders were made in the period?

In [20]:
chipo['order_id'].nunique()

1834

### Step 16. What is the average revenue amount per order?

In [22]:
# Solution 1

chipo.groupby('order_id')['item_price'].sum().mean()

np.float64(18.811428571428568)

In [27]:
chipo['item_price'].sum() / chipo['order_id'].nunique()

np.float64(18.811428571428575)

### Step 17. How many different items are sold?

In [25]:
chipo['item_name'].nunique()

50