# Ex1 - Filtering and Sorting Data

This time we are going to pull data directly from the internet.
Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [4]:

import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/thieu1995/csv-files/main/data/pandas/chipotle.tsv).

### Step 3. Assign it to a variable called chipo.

In [5]:

url = "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv"

chipo = pd.read_csv(url, sep="\t")

### Step 4. How many products cost more than $10.00?

In [6]:

chipo[chipo["item_price"] > "$10.00"].shape[0]

4035

### Step 5. What is the price of each item?
###### print a data frame with only two columns item_name and item_price

In [7]:

chipo[["item_name", "item_price"]]

                                  item_name item_price
0              Chips and Fresh Tomato Salsa     $2.39
1                                      Izze     $3.39
2                          Nantucket Nectar     $3.39
3     Chips and Tomatillo-Green Chili Salsa     $2.39
4                              Chicken Bowl    $16.98
...                                     ...        ...
4617                          Steak Burrito    $11.75
4618                          Steak Burrito    $11.75
4619                     Chicken Salad Bowl    $11.25
4620                     Chicken Salad Bowl     $8.75
4621                     Chicken Salad Bowl     $8.75

[4622 rows x 2 columns]

### Step 6. Sort by the name of the item

In [8]:

chipo.sort_values("item_name")

,order_id,quantity,item_name,choice_description,item_price
3389,1360,2,6 Pack Soft Drink,[Diet Coke],$12.98
341,148,1,6 Pack Soft Drink,[Diet Coke],$6.49
1849,749,1,6 Pack Soft Drink,[Coke],$6.49
1860,754,1,6 Pack Soft Drink,[Diet Coke],$6.49
2713,1076,1,6 Pack Soft Drink,[Coke],$6.49
...,...,...,...,...,...
2384,948,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$8.75
781,322,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Black Beans, Cheese, Sou...",$8.75
2851,1132,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",$8.49
1699,688,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$11.25
1395,567,1,Veggie Soft Tacos,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",$8.49

### Step 7. What was the quantity of the most expensive item ordered?

In [9]:

chipo.sort_values("item_price", ascending=False).head(1)["quantity"]

2624    1
Name: quantity, dtype: int64

### Step 8. How many times was a Veggie Salad Bowl ordered?

In [10]:

chipo[chipo["item_name"] == "Veggie Salad Bowl"]["quantity"].sum()

np.int64(18)

### Step 9. How many times did someone order more than one Canned Soda?

In [11]:

chipo[(chipo["item_name"] == "Canned Soda") & (chipo["quantity"] > 1)].shape[0]

20